// 获取作品
export const FETCH_WORKS = "FETCH_WORKS";
export const FETCH_WORKS_DONE = "FETCH_WORKS_DONE";
export const FETCH_WORKS_FAIL = "FETCH_WORKS_FAIL";

// 设置作品过滤器
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";

// 校验作品是否已存在
export const CHECK_WORK_EXISTS = "CHECK_WORK_EXISTS";

// 增加作品 单个
export const ADD_WORK = "ADD_WORK";
export const ADD_WORK_DONE = "ADD_WORK_DONE";
export const ADD_WORK_FAIL = "ADD_WORK_FAIL";

// 更新作品
export const UPDATE_WORK = "UPDATE_WORK";
export const UPDATE_WORK_FAIL = "UPDATE_WORK_FAIL";
export const UPDATE_WORK_DONE = "UPDATE_WORK_DONE";

// 增加标签 单个或者多个
export const ADD_TAGS = "ADD_TAGS";
export const ADD_TAGS_DONE = "ADD_TAGS_DONE";
export const ADD_TAGS_FAIL = "ADD_TAGS_FAIL";

// 更新标签
export const UPDATE_TAGS = "UPDATE_TAGS";
export const UPDATE_TAGS_FAIL = "UPDATE_TAGS_FAIL";
export const UPDATE_TAGS_DONE = "UPDATE_TAGS_DONE";

// 删除标签
export const REMOVE_TAG = "REMOVE_TAG";
export const REMOVE_TAG_DONE = "REMOVE_TAG_DONE";
export const REMOVE_TAG_FAIL = "REMOVE_TAG_FAIL";

// 获取标签
export const FETCH_TAGS = "FETCH_TAGS";
export const FETCH_TAGS_DONE = "FETCH_TAGS_DONE";
export const FETCH_TAGS_FAIL = "FETCH_TAGS_FAIL";

// 获取作者
export const FETCH_AUTHORS = "FETCH_AUTHORS";
export const FETCH_AUTHORS_FAIL = "FETCH_AUTHORS_FAIL";
export const FETCH_AUTHORS_DONE = "FETCH_AUTHORS_DONE";

export const FETCH_LANGUAGES = "FETCH_LANGUAGES";

// 增加作者 单个或者多个
export const ADD_AUTHORS = "ADD_AUTHORS";
export const ADD_AUTHORS_FAIL = "ADD_AUTHORS_FAIL";
export const ADD_AUTHORS_DONE = "ADD_AUTHORS_DONE";

// 更新作者
export const UPDATE_AUTHORS = "UPDATE_AUTHORS";
export const UPDATE_AUTHORS_FAIL = "UPDATE_AUTHORS_FAIL";
export const UPDATE_AUTHORS_DONE = "UPDATE_AUTHORS_DONE";

// 添加作者档案 单个
export const ADD_AUTHOR_PROFILE = "ADD_AUTHOR_PROFILE";
export const ADD_AUTHOR_PROFILE_FAIL = "ADD_AUTHOR_PROFILE_FAIL";
export const ADD_AUTHOR_PROFILE_DONE = "ADD_AUTHOR_PROFILE_DONE";

// 上传头像
export const UPLOAD_AVATAR = "UPLOAD_AVATAR";
export const UPLOAD_AVATAR_FAIL = "UPLOAD_AVATAR_FAIL";
export const UPLOAD_AVATAR_DONE = "UPLOAD_AVATAR_DONE";

// 获取作者档案
export const FETCH_AUTHOR_PROFILE = "FETCH_AUTHOR_PROFILE";
export const FETCH_AUTHOR_PROFILE_FAIL = "FETCH_AUTHOR_PROFILE_FAIL";
export const FETCH_AUTHOR_PROFILE_DONE = "FETCH_AUTHOR_PROFILE_DONE";

export const FETCH_AUTHOR_PROFILES = "FETCH_AUTHOR_PROFILES";
export const FETCH_AUTHOR_PROFILES_FAIL = "FETCH_AUTHOR_PROFILES_FAIL";
export const FETCH_AUTHOR_PROFILES_DONE = "FETCH_AUTHOR_PROFILES_DONE";
